name: CI & Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: npm ci

      - name: Zip for FTP
        run: zip -r deploy.zip . -x "*.git*" -x "node_modules/*"

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: ${{ secrets.CPANEL_PATH }}/
          exclude: |
            .github/**
            node_modules/**

      - name: Restart Node.js App via cPanel UAPI
        if: success()
        env:
          CP_USER: ${{ secrets.CPANEL_USERNAME }}
          CP_HOST: ${{ secrets.CPANEL_HOST }}
          CP_PATH: ${{ secrets.CPANEL_PATH }}
          CP_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
        run: |
          curl -k \
            -H "Authorization: cpanel ${CP_USER}:${CP_TOKEN}" \
            "https://${CP_HOST}:2083/execute/NodeJSApp/restart_application?application=${CP_PATH}"
